//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunday.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int Id { get; set; }
        public int MunicipalityId { get; set; }
        public int TaxPeriodId { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public System.DateTime EndDateUtc { get; set; }
        public decimal Rate { get; set; }
        public System.DateTime CreatedAtUtc { get; set; }
        public System.DateTime UpdatedAtUtc { get; set; }
        public Nullable<System.DateTime> DeletedAtUtc { get; set; }
    
        public virtual Municipality Municipality { get; set; }
        public virtual TaxPeriod TaxPeriod { get; set; }
    }
}
